apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
data:
  mongodb_uri: bW9uZ29kYjovL21vbmdvOm1vbmdvMTIzQG1vbmdvLWRiOjI3MDE3L2Rldm9wc2xlYWRlcnNpbD9hdXRoU291cmNlPWFkbWluCg==  
