apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  ports:
    - name: backend
      port: 3000
      targetPort: 3000
  selector:
    app: backend
  type: NodePort
