name: Oldscool CI-CD

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  test-and-build:
    name: Test and Build the ${{ matrix.app }}
    strategy:
      matrix:
        app: [frontend, backend]
    runs-on: ubuntu-latest
    steps:
      - name: check our the codde
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # - name: Perform basic nodejs Vulnerability scan
      #   run: npm audit --audit-level=high
      #   working-directory: ${{ matrix.app }}

      # - name: Run the unit tests
      #   run: npm test
      #   working-directory: ${{ matrix.app }}

      - run: npm ci
        working-directory: ${{ matrix.app }}

      - run: npm run build --if-present
        working-directory: ${{ matrix.app }}



  deploy:
    name: Deploy the ${{ matrix.app }} on the server
    runs-on: ubuntu-latest
    needs: [test-and-build]
    strategy:
      matrix:
        app: [frontend, backend]
    steps:
      - name: git pull on remote machine
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_REMOTE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd devops-course-app
            git pull

      - name: update the ${{ matrix.app }} on the remote machine
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_REMOTE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd devops-course-app/${{ matrix.app }}
            npm install
            sudo systemctl stop devops-course-${{ matrix.app }}
            sudo systemctl start devops-course-${{ matrix.app }}
