name: Oldscool CI-CD

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  test-and-build:
    continue-on-error: true
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - name: check our the codde
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      # - name: Perform basic nodejs Vulnerability scan
      #   run: npm audit --audit-level=high

      # - name: Run the unit tests
      #   run: npm test

      - run: npm ci

      - run: npm run build --if-present



  deploy:
    runs-on: ubuntu-latest
    needs: [test-and-build]
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

      - name: update the version on the remote machine
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST_IP }}
          username: "ubuntu"
          key: ${{ secrets.SSH_KEY_REMOTE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd devops-course-app
            git pull
            sudo systemctl stop devops-course-backend
            sudo systemctl start devops-course-backend
            sudo systemctl stop devops-course-frontend
            sudo systemctl start devops-course-frontend
