name: Oldscool CI-CD

on:
  workflow_dispatch:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    continue-on-error: true
    defaults:
      run:
        working-directory: frontend
    runs-on: ubuntu-latest
    steps:
      - name: check our the codde
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npm ci
      - run: npm run build --if-present

        name: Perform basic nodejs Vulnerability scan
      - run: npm audit --audit-level=moderate

      - name: Run the unit tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure SSH
        env:
          SSH_HOST: ${{ secrets.HOST_IP }}
          SSH_USER: "ubuntu"
          SSH_KEY: ${{ secrets.SSH_KEY_REMOTE }} 
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/github-actions-key
            StrictHostKeyChecking no
          END

      - name: List home directory
        run: ssh ec2 'ls -la'
